dist: bionic
language: python
cache: pip
python:
- '3.7'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_197c6fb131ce_key -iv $encrypted_197c6fb131ce_iv -in molecule_rsa.enc -out molecule_rsa -d
- eval `ssh-agent -s`
- ssh-add molecule_rsa
install:
- pip install molecule docker
script:
- molecule test
