---
# tasks file for ansible-role-otc-server-common
- name: Non-fedora redhat setup
  include_vars: redhat.yaml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Fedora setup
  include_vars: fedora.yaml
  when: ansible_distribution == "Fedora"

- name: Debian setup
  include_vars: debian.yaml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install often required packages
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"
  register: task_result
  until: task_result is success
  retries: 1
  delay: 2

- name: "Disable pwd login for ansible_user"
  become: true
  user:
    name: "{{ ansible_user }}"
    password_lock: yes

- name: SSH configuration
  include_tasks: sshd.yaml

- name: Journalctl configuration
  include_tasks: journalctl.yaml

- name: Place "/etc/issue" file
  become: true
  copy:
    src: etc/issue
    dest: /etc/issue
    mode: 0644

- name: Place "/etc/motd" file
  become: true
  copy:
    src: etc/motd
    dest: /etc/motd
    mode: 0644
