---
# tasks file for ansible-role-otc-server-common
- name: include OS-specific variables.
  include_vars: "{{ ansible_os_family|lower }}.yaml"
  when: ansible_os_family == 'RedHat'

- name: install often required packages
  become: yes
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: disable pwd login for user {{ ansible_user }}
  user:
    name: "{{ ansible_user }}"
    password_lock: yes

- include_tasks: sshd.yaml
- include_tasks: journalctl.yaml

- name: place "/etc/issue" file
  copy:
    src: etc/issue
    dest: /etc/issue
    mode: 0644

- name: place "/etc/motd" file
  copy:
    src: etc/motd
    dest: /etc/motd
    mode: 0644
