---
- name: firewall service
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: sshd service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: disable root login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin.*'
    replace: 'PermitRootLogin no'

- name: enable SSH forwarding (tunnel through Bastion)
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^AllowTcpForwarding.*'
    replace: 'AllowTcpForwarding yes'
    backup: yes
  when: enable_ssh_tcp_forwarding
    
- name: disable password login on bastion
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication.*'
    replace: 'PasswordAuthentication no'
  notify:
    # Restart SSHD after last replacement
    - restart sshd
